#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

MODE="${1:-run}"
if [[ "$MODE" != "run" && "$MODE" != "dry-run" ]]; then
  echo "usage: $0 [run|dry-run]" >&2
  exit 2
fi

ARTIFACT_ROOT="viewport_prediction/data/experiment_runs/netllm_vs_nbs"
V19_RUN_DIR="${V19_RUN_DIR:-}"
if [[ -z "$V19_RUN_DIR" ]]; then
  LATEST_POINTER="$ARTIFACT_ROOT/nbs_v19_latest.txt"
  if [[ ! -f "$LATEST_POINTER" ]]; then
    echo "Set V19_RUN_DIR to the completed nbs_v19 run directory." >&2
    exit 2
  fi
  V19_RUN_DIR="$(<"$LATEST_POINTER")"
fi
# Newer experiment runs contain metadata.env. Older/copied runs may retain only
# the model tree, so also support an explicit checkpoint or unique run-id lookup.
best_ar_model=""
rank_config="configs/adalora_rank_config_llama7b_min2_max32.json"
rank_budget="512"
adalora_ema_beta="0.9"
epochs="4"
learning_rate="0.0002"
seed="1"
multimodal_mode="none"
if [[ -f "$V19_RUN_DIR/metadata.env" ]]; then
  # Generated by the repository's experiment runner; values are simple scalars/paths.
  # shellcheck disable=SC1090
  source "$V19_RUN_DIR/metadata.env"
fi

SOURCE_CHECKPOINT="${NBS_CHECKPOINT:-$best_ar_model}"
if [[ -z "$SOURCE_CHECKPOINT" ]]; then
  V19_RUN_ID="$(basename "${V19_RUN_DIR%/}")"
  mapfile -t CHECKPOINT_CANDIDATES < <(
    find viewport_prediction/data/ft_plms/llama_base_low_rank_adalora_nbs_v19 \
      -type d -path "*/${V19_RUN_ID}/*/best_ar_model" 2>/dev/null | sort
  )
  if [[ "${#CHECKPOINT_CANDIDATES[@]}" -ne 1 ]]; then
    echo "NBS v19 metadata is absent and unique best_ar_model lookup failed." >&2
    echo "Set NBS_CHECKPOINT to the existing v19 best_ar_model directory." >&2
    printf 'Candidates found: %s\n' "${#CHECKPOINT_CANDIDATES[@]}" >&2
    printf '  %s\n' "${CHECKPOINT_CANDIDATES[@]}" >&2
    exit 2
  fi
  SOURCE_CHECKPOINT="${CHECKPOINT_CANDIDATES[0]}"
  echo "NBS v19 metadata absent; inferred checkpoint: $SOURCE_CHECKPOINT"
fi
PATCH_SELECTION_WEIGHTS="${PATCH_SELECTION_WEIGHTS:-patch_selection_delivery/model/best_patch_selection.pth}"
PATCH_THRESHOLD="${PATCH_THRESHOLD:-0.5}"
PATCH_TOP_K="${PATCH_TOP_K:-}"
MULTIMODAL_PROJECTOR_CHECKPOINT="${MULTIMODAL_PROJECTOR_CHECKPOINT:-}"
LATENCY_WARMUP_STEPS="${LATENCY_WARMUP_STEPS:-5}"
EVAL_PROGRESS_INTERVAL="${EVAL_PROGRESS_INTERVAL:-500}"
LIMIT_TEST_SAMPLES="${LIMIT_TEST_SAMPLES:-}"

for required in \
  "$SOURCE_CHECKPOINT/adapter_model.bin" \
  "$SOURCE_CHECKPOINT/modules_except_plm.bin" \
  "$SOURCE_CHECKPOINT/nash_rank_allocator.pt" \
  "$PATCH_SELECTION_WEIGHTS"; do
  if [[ ! -f "$required" ]]; then
    echo "Required file not found: $required" >&2
    exit 3
  fi
done
if [[ -n "$MULTIMODAL_PROJECTOR_CHECKPOINT" ]]; then
  if [[ -d "$MULTIMODAL_PROJECTOR_CHECKPOINT" ]]; then
    PROJECTOR_FILE="$MULTIMODAL_PROJECTOR_CHECKPOINT/modules_except_plm.bin"
  else
    PROJECTOR_FILE="$MULTIMODAL_PROJECTOR_CHECKPOINT"
  fi
  if [[ ! -f "$PROJECTOR_FILE" ]]; then
    echo "Multimodal projector checkpoint not found: $PROJECTOR_FILE" >&2
    exit 3
  fi
fi
if [[ ! -d viewport_prediction/data/images/Jin2022_images ]]; then
  echo "Raw Jin2022 frames not found: viewport_prediction/data/images/Jin2022_images" >&2
  exit 3
fi

RUN_ID="$(date +%Y%m%d_%H%M%S)"
RUN_DIR="${PATCH_SELECTOR_RUN_DIR:-$ARTIFACT_ROOT/nbs_v19_patch_selection_probe/$RUN_ID}"
mkdir -p "$RUN_DIR"
printf '%s\n' "$RUN_DIR" > "$ARTIFACT_ROOT/nbs_v19_patch_selection_probe_latest.txt"

LIMIT_ARGS=()
if [[ -n "$LIMIT_TEST_SAMPLES" ]]; then
  LIMIT_ARGS+=(--limit-test-samples "$LIMIT_TEST_SAMPLES")
fi
SELECTION_ARGS=(--patch-threshold "$PATCH_THRESHOLD")
if [[ -n "$PATCH_TOP_K" ]]; then
  SELECTION_ARGS=(--patch-top-k "$PATCH_TOP_K")
fi
PROJECTOR_ARGS=()
if [[ -n "$MULTIMODAL_PROJECTOR_CHECKPOINT" ]]; then
  PROJECTOR_ARGS+=(--multimodal-projector-checkpoint "$MULTIMODAL_PROJECTOR_CHECKPOINT")
fi

COMMAND=(
  python run_plm.py
  --test
  --train-dataset Jin2022
  --test-dataset Jin2022
  --plm-type llama
  --plm-size base
  --device cuda
  --device-out cuda
  --fp16
  --rank 32
  --use-adalora
  --adalora-allocator nbs
  --adalora-rank-config "${rank_config:-configs/adalora_rank_config_llama7b_min2_max32.json}"
  --adalora-rank-budget "${rank_budget:-512}"
  --adalora-ema-beta "${adalora_ema_beta:-0.9}"
  --adalora-allocation-interval 10
  --experiment-tag nbs_v19
  --model-path "$SOURCE_CHECKPOINT"
  --evaluation-tag best_ar
  --nbs-inference-mode original
  --multimodal-mode patch-selection
  --patch-selection-weights "$PATCH_SELECTION_WEIGHTS"
  "${SELECTION_ARGS[@]}"
  "${PROJECTOR_ARGS[@]}"
  --epochs "${epochs:-4}"
  --bs 1
  --grad-accum-steps 32
  --lr "${learning_rate:-0.0002}"
  --seed "${seed:-1}"
  --save-test-progress-per-steps "$EVAL_PROGRESS_INTERVAL"
  --measure-inference-latency
  --latency-warmup-steps "$LATENCY_WARMUP_STEPS"
  --results-output-dir "$RUN_DIR"
  --latency-output-path "$RUN_DIR/latency.json"
  --inference-trace-output-path "$RUN_DIR/inference_trace.json"
  --inference-tag selector
  "${LIMIT_ARGS[@]}"
)

cat > "$RUN_DIR/metadata.env" <<EOF
run_id=$RUN_ID
probe_only=true
source_v19_run=$V19_RUN_DIR
source_checkpoint=$SOURCE_CHECKPOINT
source_checkpoint_multimodal_mode=${multimodal_mode:-unknown}
patch_selection_weights=$PATCH_SELECTION_WEIGHTS
patch_threshold=$PATCH_THRESHOLD
patch_top_k=$PATCH_TOP_K
multimodal_projector_checkpoint=$MULTIMODAL_PROJECTOR_CHECKPOINT
nbs_inference_mode=original
note=NBS_v19_was_trained_without_patch_selection;_this_is_an_inference-only_probe
EOF

printf 'Evaluation artifacts: %s\n' "$RUN_DIR"
printf 'Command:'
printf ' %q' "${COMMAND[@]}"
printf '\n'
if [[ "$MODE" == "dry-run" ]]; then
  exit 0
fi

env PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True \
  "${COMMAND[@]}" 2>&1 | tee "$RUN_DIR/evaluation.log"

RESULT_CSV="$(find "$RUN_DIR" -maxdepth 1 -type f -name '*_results.csv' \
  ! -name '*_partial_results.csv' ! -name '*_per_sample_results.csv' | head -1)"
if [[ -z "$RESULT_CSV" ]]; then
  echo "Evaluation completed without an aggregate results CSV." >&2
  exit 4
fi
cp "$RESULT_CSV" "$RUN_DIR/results.csv"
PER_SAMPLE_CSV="${RESULT_CSV/_results.csv/_per_sample_results.csv}"
if [[ -f "$PER_SAMPLE_CSV" ]]; then
  cp "$PER_SAMPLE_CSV" "$RUN_DIR/per_sample_results.csv"
fi

printf '{"status":"complete","run_dir":"%s","source_checkpoint_untouched":true}\n' \
  "$RUN_DIR" > "$RUN_DIR/status.json"
echo "NBS v19 + delivered Patch Selection probe complete: $RUN_DIR"
