"""Compare performance and NBS allocation behavior across multiple runs.

The report combines four views in one figure:

1. best/final MAE and RMSE,
2. training-end rank distributions,
3. exact marginal spectral-utility gain by rank, and
4. training-end bargaining power (alpha) by allocated rank.

The marginal-utility panel consumes the CSV generated by
``plot_nbs_diminishing_marginal_gain.py`` so that every run uses the same
fixed-spectral-snapshot definition ``log(U(r+1) / U(r))``.

Example (PowerShell)::

    python analysis/plot_nbs_v6_v10_comparison.py `
      --run-dirs `
        experiment_downloads/nbs_v6/20260817_073433 `
        experiment_downloads/nbs_v7/20260817_101723 `
        experiment_downloads/nbs_v8/20260817_153454 `
        experiment_downloads/nbs_v9/20260818_025211 `
        experiment_downloads/nbs_v10/20260818_084639 `
      --labels nbs_v6 nbs_v7 nbs_v8 nbs_v9 nbs_v10 `
      --output-dir experiment_downloads/nbs_v6_v10_comparison
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


SERIES_COLORS = ("#4c78a8", "#f58518", "#54a24b", "#e45756", "#9467bd")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a single comparison report for NBS experiment runs."
    )
    parser.add_argument("--run-dirs", nargs="+", required=True, type=Path)
    parser.add_argument("--labels", nargs="+")
    parser.add_argument("--output-dir", required=True, type=Path)
    return parser.parse_args()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        return list(csv.DictReader(handle))


def read_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def percentile(values: Iterable[float], quantile: float) -> float:
    array = np.asarray(list(values), dtype=float)
    return float(np.quantile(array, quantile))


def infer_label(run_dir: Path) -> str:
    return run_dir.parent.name or run_dir.name


def read_metadata(run_dir: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    path = run_dir / "metadata.env"
    if not path.exists():
        return result
    for line in path.read_text(encoding="utf-8").splitlines():
        if "=" in line:
            key, value = line.split("=", 1)
            result[key.strip()] = value.strip()
    return result


def final_allocation_rows(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    allocation = [row for row in rows if row.get("event") == "allocation"]
    if not allocation:
        raise ValueError("Diagnostics contain no allocation events")
    final_step = max(int(row["optimizer_step"]) for row in allocation)
    return [row for row in allocation if int(row["optimizer_step"]) == final_step]


def aggregate_by_rank(
    rows: list[dict[str, str]], rank_field: str, value_field: str
) -> dict[int, dict[str, float]]:
    grouped: dict[int, list[float]] = defaultdict(list)
    for row in rows:
        value_text = row.get(value_field, "").strip()
        if not value_text:
            continue
        value = float(value_text)
        if math.isfinite(value):
            grouped[int(float(row[rank_field]))].append(value)
    result: dict[int, dict[str, float]] = {}
    for rank, values in sorted(grouped.items()):
        result[rank] = {
            "count": float(len(values)),
            "mean": float(np.mean(values)),
            "median": float(np.median(values)),
            "q25": percentile(values, 0.25),
            "q75": percentile(values, 0.75),
        }
    return result


def latest_marginal_rows(run_dir: Path) -> list[dict[str, str]]:
    path = run_dir / "diminishing_gain" / "nbs_marginal_gain_by_rank.csv"
    if not path.exists():
        raise FileNotFoundError(
            f"Missing {path}. Run analysis/plot_nbs_diminishing_marginal_gain.py first."
        )
    rows = read_csv(path)
    latest_event = max(int(float(row["validation_event"])) for row in rows)
    return [row for row in rows if int(float(row["validation_event"])) == latest_event]


def safe_label(label: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", label).strip("_") or "nbs"


def load_run(run_dir: Path, label: str) -> dict[str, Any]:
    report_path = run_dir / "checkpoint_nbs_report" / "report_summary.json"
    diagnostics_path = run_dir / "nbs_rank_diagnostics.csv"
    if not report_path.exists():
        raise FileNotFoundError(report_path)
    if not diagnostics_path.exists():
        raise FileNotFoundError(diagnostics_path)

    report = read_json(report_path)
    metadata = read_metadata(run_dir)
    final_rows = final_allocation_rows(read_csv(diagnostics_path))
    marginal_rows = latest_marginal_rows(run_dir)
    final_ranks = [int(row["rank"]) for row in final_rows]
    rank_distribution = Counter(final_ranks)
    alpha_by_rank = aggregate_by_rank(final_rows, "rank", "alpha")
    marginal_by_rank = aggregate_by_rank(
        marginal_rows, "current_rank", "marginal_utility_gain"
    )
    metrics = report["checkpoint_metrics"]
    return {
        "label": label,
        "run_dir": run_dir,
        "budget": int(metadata.get("rank_budget", report.get("final_total_rank", 0))),
        "mean_rank": float(report["final_rank_mean"]),
        "best_mae": float(metrics["best_ar"]["mae"]),
        "best_rmse": float(metrics["best_ar"]["rmse"]),
        "final_mae": float(metrics["final_nbs"]["mae"]),
        "final_rmse": float(metrics["final_nbs"]["rmse"]),
        "rank_distribution": rank_distribution,
        "alpha_by_rank": alpha_by_rank,
        "marginal_by_rank": marginal_by_rank,
        "module_count": len(final_rows),
    }


def plot_performance(axis: Any, runs: list[dict[str, Any]]) -> None:
    x = np.arange(len(runs))
    labels = [run["label"] for run in runs]
    series = (
        ("Best MAE", "best_mae", "o", "-", "#4c78a8"),
        ("Final MAE", "final_mae", "o", "--", "#4c78a8"),
        ("Best RMSE", "best_rmse", "s", "-", "#f58518"),
        ("Final RMSE", "final_rmse", "s", "--", "#f58518"),
    )
    for name, field, marker, linestyle, color in series:
        values = [run[field] for run in runs]
        axis.plot(
            x, values, label=name, marker=marker, linestyle=linestyle,
            color=color, linewidth=2, markersize=6,
        )
        for index, value in enumerate(values):
            axis.annotate(
                f"{value:.1f}", (index, value), xytext=(0, 6),
                textcoords="offset points", ha="center", fontsize=8,
            )
    axis.set_xticks(x, labels)
    axis.set(title="Prediction performance", xlabel="Experiment", ylabel="Error (lower is better)")
    axis.grid(axis="y", alpha=0.25)
    axis.legend(ncol=2, fontsize=9)


def plot_rank_distribution(axis: Any, runs: list[dict[str, Any]]) -> None:
    minimum = min(min(run["rank_distribution"]) for run in runs)
    maximum = max(max(run["rank_distribution"]) for run in runs)
    ranks = list(range(minimum, maximum + 1))
    matrix = np.asarray([
        [100.0 * run["rank_distribution"].get(rank, 0) / run["module_count"] for rank in ranks]
        for run in runs
    ])
    image = axis.imshow(matrix, aspect="auto", interpolation="nearest", cmap="Blues", vmin=0, vmax=100)
    axis.set_xticks(range(len(ranks)), ranks)
    axis.set_yticks(range(len(runs)), [run["label"] for run in runs])
    axis.set(title="Training-end rank distribution", xlabel="Allocated rank", ylabel="Experiment")
    for row in range(matrix.shape[0]):
        for column in range(matrix.shape[1]):
            value = matrix[row, column]
            if value >= 1.0:
                axis.text(
                    column, row, f"{value:.0f}%", ha="center", va="center",
                    fontsize=8, color="white" if value >= 55 else "black",
                )
    plt.colorbar(image, ax=axis, label="LoRA modules (%)", fraction=0.046, pad=0.04)


def plot_marginal_utility(axis: Any, runs: list[dict[str, Any]]) -> None:
    for index, run in enumerate(runs):
        stats = run["marginal_by_rank"]
        ranks = np.asarray(list(stats), dtype=float)
        median = np.asarray([stats[rank]["median"] for rank in stats])
        q25 = np.asarray([stats[rank]["q25"] for rank in stats])
        q75 = np.asarray([stats[rank]["q75"] for rank in stats])
        positive = median > 0
        ranks, median, q25, q75 = ranks[positive], median[positive], q25[positive], q75[positive]
        color = SERIES_COLORS[index % len(SERIES_COLORS)]
        axis.plot(ranks, median, label=run["label"], color=color, linewidth=2)
        axis.fill_between(ranks, np.maximum(q25, np.finfo(float).tiny), q75, color=color, alpha=0.12)
    axis.set_yscale("log")
    axis.set(
        title="Marginal spectral-utility gain by rank (latest snapshot)",
        xlabel="Current rank r (gain for r → r+1)",
        ylabel="Median log(U(r+1) / U(r))",
    )
    axis.grid(alpha=0.25, which="both")
    axis.legend(fontsize=9)


def plot_bargaining_power(axis: Any, runs: list[dict[str, Any]]) -> None:
    for index, run in enumerate(runs):
        stats = run["alpha_by_rank"]
        ranks = np.asarray(list(stats), dtype=float)
        means = np.asarray([stats[rank]["mean"] for rank in stats])
        q25 = np.asarray([stats[rank]["q25"] for rank in stats])
        q75 = np.asarray([stats[rank]["q75"] for rank in stats])
        color = SERIES_COLORS[index % len(SERIES_COLORS)]
        axis.plot(ranks, means, label=run["label"], color=color, marker="o", linewidth=1.8)
        axis.fill_between(ranks, q25, q75, color=color, alpha=0.12)
    axis.axhline(1.0 / 64.0, color="#666666", linestyle=":", linewidth=1.3, label="Uniform α = 1/64")
    axis.set(
        title="Bargaining power by final allocated rank",
        xlabel="Training-end allocated rank",
        ylabel="Mean bargaining power α",
    )
    axis.grid(alpha=0.25)
    axis.legend(fontsize=9, ncol=2)


def write_csv_outputs(runs: list[dict[str, Any]], output_dir: Path) -> list[Path]:
    performance_path = output_dir / "nbs_v6_v10_performance.csv"
    with performance_path.open("w", newline="", encoding="utf-8") as handle:
        fields = ["label", "budget", "mean_rank", "best_mae", "best_rmse", "final_mae", "final_rmse"]
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows({field: run[field] for field in fields} for run in runs)

    distribution_path = output_dir / "nbs_v6_v10_final_rank_distribution.csv"
    with distribution_path.open("w", newline="", encoding="utf-8") as handle:
        fields = ["label", "rank", "module_count", "module_fraction"]
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for run in runs:
            for rank, count in sorted(run["rank_distribution"].items()):
                writer.writerow({
                    "label": run["label"], "rank": rank, "module_count": count,
                    "module_fraction": count / run["module_count"],
                })

    marginal_path = output_dir / "nbs_v6_v10_marginal_utility_by_rank.csv"
    bargaining_path = output_dir / "nbs_v6_v10_bargaining_power_by_rank.csv"
    for path, key in ((marginal_path, "marginal_by_rank"), (bargaining_path, "alpha_by_rank")):
        with path.open("w", newline="", encoding="utf-8") as handle:
            fields = ["label", "rank", "count", "mean", "median", "q25", "q75"]
            writer = csv.DictWriter(handle, fieldnames=fields)
            writer.writeheader()
            for run in runs:
                for rank, stats in run[key].items():
                    writer.writerow({"label": run["label"], "rank": rank, **stats})
    return [performance_path, distribution_path, marginal_path, bargaining_path]


def main() -> None:
    args = parse_args()
    if args.labels and len(args.labels) != len(args.run_dirs):
        raise ValueError("--labels must contain exactly one label per run directory")
    labels = args.labels or [infer_label(path) for path in args.run_dirs]
    args.output_dir.mkdir(parents=True, exist_ok=True)
    runs = [load_run(path, label) for path, label in zip(args.run_dirs, labels)]

    figure, axes = plt.subplots(2, 2, figsize=(18, 12), constrained_layout=True)
    figure.suptitle("NBS-NetLLM v6–v10: performance and allocation comparison", fontsize=16)
    plot_performance(axes[0, 0], runs)
    plot_rank_distribution(axes[0, 1], runs)
    plot_marginal_utility(axes[1, 0], runs)
    plot_bargaining_power(axes[1, 1], runs)

    figure_path = args.output_dir / "nbs_v6_v10_comparison.png"
    figure.savefig(figure_path, dpi=200)
    plt.close(figure)
    print(f"Comparison figure saved at {figure_path}")
    for path in write_csv_outputs(runs, args.output_dir):
        print(f"Comparison data saved at {path}")


if __name__ == "__main__":
    main()
