"""Audit and visualize whether the NBS rank-allocation mechanism is active.

The input is a ``nbs_rank_diagnostics.csv`` produced by ``run_plm.py``.  The
script checks both identities used by the allocator:

    next_marginal_utility_gain = log((U(r) + next_utility_increment) / U(r))
    next_marginal_gain = alpha * next_marginal_utility_gain

It also checks the global budget and layer bounds, then visualizes the factors,
rank trajectory, allocation churn, and validation behavior.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import re
from collections import OrderedDict
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


REQUIRED_FIELDS = {
    "optimizer_step", "phase", "event", "layer_name", "rank", "min_rank",
    "max_rank", "rank_delta", "total_rank", "rank_budget", "alpha",
    "utility", "next_utility_increment", "next_marginal_utility_gain",
    "next_marginal_gain",
}
MODULE_COLORS = {"q_proj": "#1f77b4", "v_proj": "#ff7f0e"}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Visual evidence that NBS utility/sensitivity rank allocation is active."
    )
    parser.add_argument("--diagnostics", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--label", default="NBS")
    return parser.parse_args()


def optional_float(value: str | None) -> float:
    if value is None or value.strip() == "":
        return math.nan
    return float(value)


def module_coordinates(row: dict[str, str]) -> tuple[int, int, str]:
    layer_text = row.get("transformer_layer_index", "").strip()
    if layer_text:
        layer_index = int(float(layer_text))
    else:
        match = re.search(r"(?:^|\.)layers\.(\d+)(?:\.|$)", row["layer_name"])
        layer_index = int(match.group(1)) if match else 10**9
    module_type = row.get("module_type", "").strip() or row["layer_name"].rsplit(".", 1)[-1]
    return layer_index, {"q_proj": 0, "v_proj": 1}.get(module_type, 99), module_type


def load_events(path: Path) -> tuple[
    list[dict[str, str]],
    OrderedDict[tuple[int, str], list[dict[str, str]]],
]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        missing = REQUIRED_FIELDS.difference(reader.fieldnames or [])
        if missing:
            raise ValueError(
                f"{path} is missing columns {sorted(missing)}. "
                "Use diagnostics generated by the marginal-utility logging code."
            )
        rows = list(reader)
    if not rows:
        raise ValueError(f"No diagnostics found in {path}")
    events: OrderedDict[tuple[int, str], list[dict[str, str]]] = OrderedDict()
    for row in rows:
        events.setdefault((int(row["optimizer_step"]), row["event"]), []).append(row)
    return rows, events


def finite_identity_data(rows: list[dict[str, str]]) -> dict[str, np.ndarray]:
    values: dict[str, list[float]] = {
        "utility_gain": [], "utility_reconstructed": [],
        "nash_gain": [], "nash_reconstructed": [],
    }
    for row in rows:
        utility = optional_float(row.get("utility"))
        increment = optional_float(row.get("next_utility_increment"))
        utility_gain = optional_float(row.get("next_marginal_utility_gain"))
        alpha = optional_float(row.get("alpha"))
        nash_gain = optional_float(row.get("next_marginal_gain"))
        if not all(math.isfinite(value) for value in (
            utility, increment, utility_gain, alpha, nash_gain
        )):
            continue
        if utility <= 0 or utility + increment <= 0:
            continue
        values["utility_gain"].append(utility_gain)
        values["utility_reconstructed"].append(math.log((utility + increment) / utility))
        values["nash_gain"].append(nash_gain)
        values["nash_reconstructed"].append(alpha * utility_gain)
    return {key: np.asarray(value, dtype=float) for key, value in values.items()}


def relative_error(actual: np.ndarray, expected: np.ndarray) -> np.ndarray:
    return np.abs(actual - expected) / np.maximum(np.abs(actual), 1e-30)


def build_event_audit(
    events: OrderedDict[tuple[int, str], list[dict[str, str]]]
) -> list[dict[str, Any]]:
    audit = []
    for (step, event), group in events.items():
        ranks = [int(row["rank"]) for row in group]
        min_ranks = [int(row["min_rank"]) for row in group]
        max_ranks = [int(row["max_rank"]) for row in group]
        gains = [optional_float(row.get("next_marginal_gain")) for row in group]
        finite_gains = [value for value in gains if math.isfinite(value)]
        audit.append({
            "optimizer_step": step,
            "event": event,
            "phase": group[0]["phase"],
            "total_rank": int(group[0]["total_rank"]),
            "rank_budget": int(group[0]["rank_budget"]),
            "budget_ok": int(group[0]["total_rank"]) == int(group[0]["rank_budget"]),
            "bounds_ok": all(
                minimum <= rank <= maximum
                for rank, minimum, maximum in zip(ranks, min_ranks, max_ranks)
            ),
            "changed_modules": sum(int(row["rank_delta"]) != 0 for row in group),
            "reallocated_rank_units": 0.5 * sum(
                abs(int(row["rank_delta"])) for row in group
            ),
            "mean_next_marginal_gain": (
                sum(finite_gains) / len(finite_gains) if finite_gains else math.nan
            ),
            "max_next_marginal_gain": max(finite_gains, default=math.nan),
        })
    return audit


def write_event_audit(rows: list[dict[str, Any]], path: Path) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def parity_plot(axis: Any, actual: np.ndarray, expected: np.ndarray,
                title: str, xlabel: str, ylabel: str) -> None:
    valid = np.isfinite(actual) & np.isfinite(expected) & (actual > 0) & (expected > 0)
    actual = actual[valid]
    expected = expected[valid]
    axis.scatter(expected, actual, s=10, alpha=0.28, edgecolors="none")
    if actual.size:
        lower = min(float(actual.min()), float(expected.min()))
        upper = max(float(actual.max()), float(expected.max()))
        axis.plot([lower, upper], [lower, upper], linestyle="--", linewidth=1.2, color="#444444")
        axis.set_xscale("log")
        axis.set_yscale("log")
    axis.set(title=title, xlabel=xlabel, ylabel=ylabel)
    axis.grid(alpha=0.25)


def create_figure(
    rows: list[dict[str, str]],
    events: OrderedDict[tuple[int, str], list[dict[str, str]]],
    audit: list[dict[str, Any]],
    identities: dict[str, np.ndarray],
    label: str,
    output_path: Path,
) -> None:
    figure, axes = plt.subplots(3, 2, figsize=(17, 18), constrained_layout=True)
    figure.suptitle(f"{label} — NBS allocation mechanism evidence", fontsize=16)

    parity_plot(
        axes[0, 0], identities["utility_gain"], identities["utility_reconstructed"],
        "Spectral utility identity",
        "log((U + next increment) / U)", "Recorded utility-only marginal gain",
    )
    parity_plot(
        axes[0, 1], identities["nash_gain"], identities["nash_reconstructed"],
        "Sensitivity-weighted Nash identity",
        "alpha × utility-only gain", "Recorded next marginal Nash gain",
    )

    allocation_events = [
        (key, group) for key, group in events.items() if key[1] == "allocation"
    ]
    if not allocation_events:
        raise ValueError("No allocation events were found")
    (_, _), final_group = allocation_events[-1]

    factor_axis = axes[1, 0]
    for module_type in ("q_proj", "v_proj"):
        selected = [
            row for row in final_group if module_coordinates(row)[2] == module_type
        ]
        factor_axis.scatter(
            [optional_float(row["next_marginal_utility_gain"]) for row in selected],
            [optional_float(row["alpha"]) for row in selected],
            s=[28 + 10 * (int(row["rank"]) - int(row["min_rank"])) for row in selected],
            alpha=0.72,
            label=module_type,
            color=MODULE_COLORS[module_type],
        )
    factor_axis.set_xscale("log")
    factor_axis.set_yscale("log")
    factor_axis.set(
        title="Two factors entering the Nash gain (final allocation event)",
        xlabel="Utility-only marginal gain (log ratio)",
        ylabel="Sensitivity bargaining weight alpha",
    )
    factor_axis.grid(alpha=0.25)
    factor_axis.legend(title="Marker size = rank above minimum")

    module_names = sorted(
        {row["layer_name"] for row in rows},
        key=lambda name: next(
            (*module_coordinates(row), name)
            for row in rows if row["layer_name"] == name
        ),
    )
    event_keys = list(events)
    rank_lookup = {
        (key, row["layer_name"]): int(row["rank"])
        for key, group in events.items() for row in group
    }
    rank_matrix = np.asarray([
        [rank_lookup.get((key, name), np.nan) for key in event_keys]
        for name in module_names
    ], dtype=float)
    heatmap_axis = axes[1, 1]
    image = heatmap_axis.imshow(
        rank_matrix, aspect="auto", interpolation="nearest", cmap="viridis"
    )
    tick_count = min(10, len(event_keys))
    ticks = sorted(set(np.linspace(0, len(event_keys) - 1, tick_count, dtype=int)))
    heatmap_axis.set_xticks(ticks)
    heatmap_axis.set_xticklabels(
        [f"{event_keys[index][0]}\n{event_keys[index][1]}" for index in ticks],
        rotation=45, ha="right", fontsize=8,
    )
    heatmap_axis.set(
        title="Rank trajectory across allocation/validation events",
        xlabel="Optimizer step / event", ylabel="LoRA modules (layer × q/v)",
    )
    heatmap_axis.set_yticks([])
    figure.colorbar(image, ax=heatmap_axis, label="Allocated rank")

    churn_axis = axes[2, 0]
    allocation_audit = [row for row in audit if row["event"] == "allocation"]
    churn_axis.bar(
        [row["optimizer_step"] for row in allocation_audit],
        [row["reallocated_rank_units"] for row in allocation_audit],
        width=max(1.0, max(row["optimizer_step"] for row in allocation_audit) * 0.012),
        color="#4c78a8",
    )
    churn_axis.set(
        title="Rank movement at each NBS allocation",
        xlabel="Optimizer step", ylabel="Rank units moved",
    )
    churn_axis.grid(axis="y", alpha=0.25)

    validation_axis = axes[2, 1]
    validation_points = []
    seen_validation_events = set()
    for group in events.values():
        row = group[0]
        event_text = row.get("validation_event", "").strip()
        if not event_text or event_text in seen_validation_events:
            continue
        seen_validation_events.add(event_text)
        validation_points.append((
            int(event_text),
            optional_float(row.get("validation_loss")),
            optional_float(row.get("teacher_forcing_validation_loss")),
        ))
    if validation_points:
        validation_axis.plot(
            [point[0] for point in validation_points],
            [point[1] for point in validation_points],
            marker="o", label="Autoregressive", color="#d95f02",
        )
        validation_axis.plot(
            [point[0] for point in validation_points],
            [point[2] for point in validation_points],
            marker="o", label="Teacher forcing", color="#1b9e77",
        )
        validation_axis.legend()
    validation_axis.set(
        title="Validation behavior while ranks are reallocated",
        xlabel="Validation event", ylabel="Circular viewport MSE",
    )
    validation_axis.grid(alpha=0.25)

    figure.savefig(output_path, dpi=180)
    plt.close(figure)


def main() -> None:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    rows, events = load_events(args.diagnostics)
    identities = finite_identity_data(rows)
    audit = build_event_audit(events)

    utility_error = relative_error(
        identities["utility_gain"], identities["utility_reconstructed"]
    )
    nash_error = relative_error(
        identities["nash_gain"], identities["nash_reconstructed"]
    )
    allocation_events = [row for row in audit if row["event"] == "allocation"]
    changed_events = [row for row in allocation_events if row["changed_modules"] > 0]
    final_allocation = allocation_events[-1]
    final_group = events[(final_allocation["optimizer_step"], "allocation")]
    final_ranks = [int(row["rank"]) for row in final_group]

    summary = {
        "diagnostics": str(args.diagnostics),
        "row_count": len(rows),
        "event_count": len(events),
        "allocation_event_count": len(allocation_events),
        "allocation_events_with_rank_changes": len(changed_events),
        "all_rank_budgets_satisfied": all(row["budget_ok"] for row in audit),
        "all_layer_bounds_satisfied": all(row["bounds_ok"] for row in audit),
        "maximum_utility_identity_relative_error": (
            float(utility_error.max()) if utility_error.size else None
        ),
        "maximum_nash_identity_relative_error": (
            float(nash_error.max()) if nash_error.size else None
        ),
        "final_allocation_step": final_allocation["optimizer_step"],
        "final_rank_minimum": min(final_ranks),
        "final_rank_maximum": max(final_ranks),
        "final_rank_mean": sum(final_ranks) / len(final_ranks),
        "final_total_rank": final_allocation["total_rank"],
        "rank_budget": final_allocation["rank_budget"],
        "nbs_mechanism_active": bool(
            allocation_events
            and changed_events
            and all(row["budget_ok"] and row["bounds_ok"] for row in audit)
            and (not nash_error.size or float(nash_error.max()) < 1e-5)
        ),
    }

    summary_path = args.output_dir / "nbs_mechanism_summary.json"
    summary_path.write_text(
        json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    audit_path = args.output_dir / "nbs_mechanism_event_audit.csv"
    write_event_audit(audit, audit_path)
    figure_path = args.output_dir / "nbs_mechanism_evidence.png"
    create_figure(rows, events, audit, identities, args.label, figure_path)

    status = "PASS" if summary["nbs_mechanism_active"] else "WARN"
    print(f"[{status}] NBS mechanism active: {summary['nbs_mechanism_active']}")
    print(f"Summary saved at {summary_path}")
    print(f"Event audit saved at {audit_path}")
    print(f"Figure saved at {figure_path}")


if __name__ == "__main__":
    main()
